### ISSUE TITLE
unable to run @augu/clippy-action

### ISSUE THREAD

**Issue by h4rldev** [auguwu/clippy-action#30]
![image](https://github.com/auguwu/clippy-action/assets/98224660/a8419cf9-c9c0-43de-a438-bbdb71af9387)

> Workflow File
```

name: rust-clippy analyze

permissions: read-all

on:
  push:
    branches: [dev]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: 18 7 * * 6

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: auguwu/clippy-action@1.1.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
```
