### ISSUE TITLE
Args is broken

### ISSUE THREAD

**Issue by ggreco** [auguwu/clippy-action#495]
If I try to use the option `args` when using the action:

```
      - uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --locked
```

I get an error, since the option is passed after `--`:

```
  $ /home/runner/.cargo/bin/cargo clippy --message-format json -- --locked
[...]
  error: Unrecognized option: 'locked'
```

... the same happens if I try to use --all-features --all-targets (like the example of the archived version in actions-rs does):

```
error: Unrecognized option: 'all-features'
```

...the solution is probably just to expand `args` value before --:

```
cargo clippy --message-format json --locked --
```

... works properly.
